INSERT INTO city (name) VALUES
('Acajete'),
('Acatlán'),
('Acayucan'),
('Actopan'),
('Acula'),
('Acultzingo'),
('Camarón de Tejeda'),
('Alpatláhuac'),
('Alto Lucero de Gutiérrez Barrios'),
('Altotonga'),
('Alvarado'),
('Amatitlán'),
('Naranjos Amatlán'),
('Amatlán de los Reyes'),
('Angel R. Cabada'),
('La Antigua'),
('Apazapan'),
('Aquila'),
('Astacinga'),
('Atlahuilco'),
('Atoyac'),
('Atzacan'),
('Atzalan'),
('Tlaltetela'),
('Ayahualulco'),
('Banderilla'),
('Benito Juárez'),
('Boca del Río'),
('Calcahualco'),
('Camerino Z. Mendoza'),
('Carrillo Puerto'),
('Castiello de Bravo'),
('Catemaco'),
('Cazones de Herrera'),
('Cerro Azul'),
('Citlaltépetl'),
('Coacoatzintla'),
('Coahuitlán'),
('Coatepec'),
('Coatzintla'),
('Coetzala'),
('Cofre de Perote'),
('Colipa'),
('Comapa'),
('Córdoba'),
('Cosamaloapan de Carpio'),
('Cosautlán de Carvajal'),
('Coscomatepec'),
('Cosoleacaque'),
('Cotaxtla'),
('Coxquihui'),
('Coyutla'),
('Cuilápan'),
('Cuitláhuac'),
('Chacaltianguis'),
('Chalma'),
('Chiconamel'),
('Chiconquiaco'),
('Chicontepec'),
('Chinameca'),
('Chinampa de Gorostiza'),
('Chocamán'),
('Chontla'),
('Chumatlán'),
('Emiliano Zapata'),
('Esperanza'),
('Filomeno Mata'),
('Fortín'),
('Gutiérrez Zamora'),
('Hidalgotitlán'),
('Huatusco'),
('Huayacocotla'),
('Hueyapan de Ocampo'),
('Huiloapan de Cuauhtémoc'),
('Ignacio de la Llave'),
('Ilamatlán'),
('Isla'),
('Ixcatepec'),
('Ixhuacán de los Reyes'),
('Ixhuatlán de Madero'),
('Ixhuatlán del Café'),
('Ixhuatlancillo'),
('Ixhuatlán del Sureste'),
('Ixmatlahuacan'),
('Ixtaczoquitlán'),
('Jamapa'),
('Jesús Carranza'),
('Xalapa'),
('Xico'),
('Jilotepec'),
('Juan Rodríguez Clara'),
('Juchique de Ferrer'),
('La Perla'),
('Landero y Coss'),
('Lerdo de Tejada'),
('Magdalena'),
('Maltrata'),
('Manlio Fabio Altamirano'),
('Mariano Escobedo'),
('Martínez de la Torre'),
('Mecatlán'),
('Medellín'),
('Misantla'),
('Mixtla de Altamirano'),
('Moloacán'),
('Naolinco'),
('Naranjal'),
('Nautla'),
('Nogales'),
('Oluta'),
('Omealca'),
('Orizaba'),
('Otatitlán'),
('Oteapan'),
('Ozuluama de Mascareñas'),
('Pajapan'),
('Pánuco'),
('Papantla'),
('Paso del Macho'),
('Paso de Ovejas'),
('Perote'),
('Platón Sánchez'),
('Playa Vicente'),
('Poza Rica de Hidalgo'),
('Los Reyes'),
('Rafael Delgado'),
('Rafael Lucio'),
('El Espinal'),
('Río Blanco'),
('Saltabarranca'),
('San Andrés Tenejapan'),
('San Juan Evangelista'),
('Santiago Tuxtla'),
('Sayula de Alemán'),
('Sochiapa'),
('Soconusco'),
('Sochiapan'),
('Sohuapan'),
('Sonora'),
('Tamalín'),
('Tamasopo'),
('Tamiahua'),
('Tampico Alto'),
('Tancoco'),
('Tantima'),
('Tantoyuca'),
('Tatatila'),
('Castillo de Teayo'),
('Tecolutla'),
('Tehuipango'),
('Álamo Temapache'),
('Tempoal'),
('Tenampa'),
('Tenochtitlán'),
('Teocelo'),
('Tepatlaxco'),
('Tepetlán'),
('Tepetzintla'),
('Tequila'),
('José Azueta'),
('Texcatepec'),
('Texhuacán'),
('Texistepec'),
('Tezonapa'),
('Tihuatlán'),
('Tlacojalpan'),
('Tlacolulan'),
('Tlacotalpan'),
('Tlacotepec de Mejía'),
('Tlachichilco'),
('Tlalixcoyan'),
('Tlalnelhuayocan'),
('Tlapacoyan'),
('Tlaquilpa'),
('Tlilapan'),
('Tomatlán'),
('Tonayán'),
('Totutla'),
('Tuxpan'),
('Tuxtilla'),
('Ursulo Galván'),
('Vega de Alatorre'),
('Veracruz'),
('Villa Aldama'),
('Xoxocotla'),
('Yanga'),
('Yecuatla'),
('Zacualpan'),
('Zaragoza'),
('Zentla'),
('Zongolica'),
('Zontecomatlán de López y Fuentes'),
('Zozocolco de Hidalgo'),
('Agua Dulce'),
('El Higo'),
('Nanchital de Lázaro Cárdenas del Río'),
('Tierra Blanca'),
('Coatzacoalcos'),
('Las Choapas'),
('Minatitlán'),
('Soteapan'),
('Jaltipan'),
('San Andrés Tuxtla');

insert into account (name, lastName, type, email, phone, password) values ("admin", "admin", "agent", "david@hotmail.com", "2255447788", "contrasena");

insert into account (name, lastName, type, email, phone, password) values ("Emmanuel", "Pale","client", "pale@hotmail.com", "2255447788", "habitacionDeVuelo");

insert into houseOwner (name, email, phone) values ("david carrion", "davidcarrion@hotmail.com", "2288554477");

insert into property (title, shortDescription, fullDescription, type, price, state, direction, houseOwner, action, numRooms, numBathrooms, garage, garden, city, size)
values ("casita en xalapa", "casa a la orilla de los lagos en xalapa veracruz", "casa en el centro, en la orilla de los lagos, cuenta con todos los servicios basicos y tiene cerca muchas tiendas", "house", 2500, "available", "xalapa veracruz colonia centro, calle benito juarez num 5", 1, "rent", 2, 1, true, false, "Xalapa", 20);

insert into property (title, shortDescription, fullDescription, type, price, state, direction, houseOwner, action, numRooms, numBathrooms, garage, garden, city, size)
values ("Casa rustica", "casa rustica a la orilla de xalapa", "casa rustica a la orilla de xalapa, todos los servicios basicos disponibles: internet, agua potable, electricidad, television por cable, multiples negocios cerca", "house", 5000, "available", "xalapa, ver. col. el haya", 1, "rent", 3, 1, false, true, "Xalapa", 30);

insert into property (title, shortDescription, fullDescription, type, price, state, direction, houseOwner, action, numRooms, numBathrooms, garage, garden, city, size)
values ("Edificio rustico", "edificio rustico a la orilla de coatepec", "caso rustico a la orilla de coatepec, todos los servicios basicos disponibles: internet, agua potable, electricidad, television por cable, multiples negocios cerca", "building", 5000, "available", "coatepec, ver. col. el haya", 1, "rent", 36, 12, false, false, "Xalapa", 15);
